name: Robert Blake
favicon: null
layout_spectrum: 0.99585
typography_spectrum: 0.23576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001762'
    - '#324da7'
    - '#0035e2'
    - '#4469e2'
    - '#000208'
  brandStrength: 0.25
  lightness: 0.4409693325869739
  saturation: 0.6975815109908581
  rhythmicContrast: 0.32285929122008383
purpose: []
